# The location to store retrieved data.
# If the path is relative, then it is relative to output/
output-path = "/tmp/wikidot/results-en.sqlite"

# Which wikidot site(s) to pull data for.
sites = ["scp-wiki"]
