# The location to store retrieved data.
# If the path is relative, then it is relative to output/
output-path = "/tmp/wikidot/results-en.json"

# How many pages to download in between saving data to disk.
save-page-offset = "1000"

# Which wikidot site(s) to pull data for.
sites = ["scp-wiki"]
